### ISSUE TITLE
Building your own Legends

### ISSUE THREAD

**Issue by patrickmohrmann** [earthdawn-vtt/fvtt-earthdawn4e#426]
LP Tracking shall cover all possibilities of the section in the Players Guide "Building your own Legend"

the following list shall be included:

- [x] The Actor Sheet for Characters shall have a Section for Legend Points
  - [x] this section shall contain fields for **current LP**, **Spend LP**, **total LP**, and **Legend Status**
  - [ ] in addition to the above mentioned information, it shall also house the list of all Permanent Patterns (like group patterns) this might go into the specials tab
  - [x] A Legend point History for all received Legendpoints shall be available as well in this section.
  - [x] Another History shall be available and shall show all spend legendspoints.

- [x] An Option (button, chat command etc.) shall be available to provide players legend points together with a note to remember the session.

- [ ] Spending legend points shall be triggered for the following situations:
  - [x] Improving Attribute Values
  - [x] Improving Talent Ranks
  - [x] Improving Skill Ranks
  - [x] Learning new Spells
  - [x] Learning new Knacks
  - [x] Learning new Spell Knacks
  - [ ] Weaving Threads
  - [x] Advancing Disciplines
  - [x] learning Questors 
  - [x] Learning Paths 
  - [x] Learning new Disciplines
  - [x] Versatility
  - [x] Legendardy Status
