### ISSUE TITLE
turn off Legendpoint Restrictions with system settings

### ISSUE THREAD

**Issue by patrickmohrmann** [earthdawn-vtt/fvtt-earthdawn4e#788]
it shall be possible to turn of the following Legend Point Restricitons:

- [ ] Max Skill Level
- [ ] Max Talent Level
- [ ] Max Devotion Level
- [ ] Max Threads
